version: '3'
services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
    networks:
      - local
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  docker-gc:
#    image: spotify/docker-gc
#    container_name: "docker-gc"
#    environment:
#      - DRY_RUN = 1
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
