version: '3.6'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ubuntu.jack'
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qq.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "jackxia5@foxmail.com"
        gitlab_rails['smtp_password'] = "1#@erwda*"
        gitlab_rails['smtp_domain'] = "smtp.qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'jackxia5@foxmail.com'
        gitlab_rails['gitlab_email_display_name'] = 'JackXia'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        user['git_user_email'] = "jackxia5@foxmail.com"
        nginx['enable'] = true
        nginx['client_max_body_size'] = '250m'
        #nginx['redirect_http_to_https'] = true
        #nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        #nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
        #nginx['ssl_ciphers'] = "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"
        #nginx['ssl_prefer_server_ciphers'] = "on"
        #nginx['ssl_protocols'] = "TLSv1.1 TLSv1.2"
        #nginx['ssl_session_cache'] = "builtin:1000  shared:SSL:10m"
        #nginx['listen_addresses'] = ["0.0.0.0"]
        #nginx['http2_enabled'] = true
    ports:
      - "55580:80"
      #- "55443:443"
      - "55522:22"
    volumes:
      - "/data/gitlab/config:/etc/gitlab"
      - "/data/gitlab/logs:/var/log/gitlab"
      - "/data/gitlab/data:/var/opt/gitlab"
  #gitlab-runner:
    #image: gitlab/gitlab-runner:alpine
